/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single recipe by its identifier */
        get: operations["getById"];
        /**
         * Replace an existing recipe
         * @description Replaces the recipe including its ingredients and preparation steps.
         */
        put: operations["update"];
        post?: never;
        /** Delete a recipe */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all recipes */
        get: operations["getAll"];
        put?: never;
        /**
         * Create a recipe
         * @description Creates a new recipe and returns it including the generated identifier.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/tools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Call a tool
         * @description Runs the tool and returns its result. The request body carries the arguments as a JSON object, exactly as the tool's inputSchema describes them; a tool without arguments takes an empty object. A failure the caller can act on – an unknown identifier, an argument the schema rejects – is answered with 200 and isError set, because the tool ran and reported it. That is how the protocol answers as well.
         */
        post: operations["callTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the tools of the MCP server
         * @description The same list a protocol client gets from tools/list, including the JSON Schema each tool validates its arguments against.
         */
        get: operations["tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the MCP server says about itself
         * @description Name, version and the starting hint a protocol client receives from initialize. Read this first: the instructions name the tools to begin with.
         */
        get: operations["server"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the resources of the MCP server
         * @description The pages of the delivered system documentation, one resource each. The list is built when the application starts and is empty in a deployable built without documentation.
         */
        get: operations["resources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mcp/resources/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a resource
         * @description Returns the content blocks of one resource. Takes the URI from the resource list.
         */
        get: operations["resourceContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A single ingredient of a recipe */
        Ingredient: {
            /**
             * @description Ingredient name
             * @example Spaghetti
             */
            name: string;
            /**
             * @description Amount of the ingredient
             * @example 500
             */
            quantity?: number;
            /**
             * @description Unit of the quantity
             * @example g
             */
            unit?: string;
        };
        /** @description A single preparation step; its order is the list position */
        PreparationStep: {
            /**
             * @description Textual instruction
             * @example Boil the pasta
             */
            instruction: string;
        };
        /** @description Recipe payload for create and update operations */
        RecipeRequest: {
            /**
             * @description Title of the recipe
             * @example Spaghetti Carbonara
             */
            title: string;
            /**
             * @description Free-text description
             * @example Classic Roman pasta
             */
            description?: string;
            /**
             * Format: int32
             * @description Number of servings
             * @example 4
             */
            servings?: number;
            /**
             * Format: int32
             * @description Preparation time in minutes
             * @example 25
             */
            prepTimeMinutes?: number;
            /**
             * @description Difficulty level
             * @example MEDIUM
             * @enum {string}
             */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /** @description Ingredients of the recipe */
            ingredients?: components["schemas"]["Ingredient"][];
            /** @description Preparation steps; their order in this list defines the position */
            steps?: components["schemas"]["PreparationStep"][];
        };
        /** @description A single field-level validation error */
        FieldError: {
            /**
             * @description Name of the offending field
             * @example title
             */
            field: string;
            /**
             * @description Validation message
             * @example must not be blank
             */
            message: string;
        };
        /** @description Error payload following RFC 9457 */
        ProblemDetail: {
            /**
             * @description URI reference identifying the problem type
             * @example /recipes/docs/#problem-not-found
             */
            type: string;
            /**
             * @description Human-readable summary of the problem type
             * @example Recipe not found
             */
            title: string;
            /**
             * Format: int32
             * @description HTTP status code
             * @example 404
             */
            status: number;
            /**
             * @description Human-readable explanation of this occurrence
             * @example Recipe 42 not found
             */
            detail: string;
            /**
             * @description URI reference of the request that produced the problem
             * @example /recipes/api/recipes/42
             */
            instance: string;
            /** @description Per-field validation errors; empty unless a validation failed */
            fieldErrors: components["schemas"]["FieldError"][];
        };
        /** @description A preparation step including its resolved order */
        PreparationStepResponse: {
            /**
             * Format: int32
             * @description 1-based order of the step
             * @example 1
             */
            position: number;
            /**
             * @description Textual instruction
             * @example Boil the pasta
             */
            instruction: string;
        };
        /** @description A persisted recipe */
        RecipeResponse: {
            /**
             * Format: int64
             * @description Database identifier
             * @example 1
             */
            id: number;
            /**
             * @description Title of the recipe
             * @example Spaghetti Carbonara
             */
            title: string;
            /**
             * @description Free-text description
             * @example Classic Roman pasta
             */
            description?: string;
            /**
             * Format: int32
             * @description Number of servings
             * @example 4
             */
            servings?: number;
            /**
             * Format: int32
             * @description Preparation time in minutes
             * @example 25
             */
            prepTimeMinutes?: number;
            /**
             * @description Difficulty level
             * @example MEDIUM
             * @enum {string}
             */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /** @description Ingredients of the recipe */
            ingredients: components["schemas"]["Ingredient"][];
            /** @description Preparation steps in ascending order */
            steps: components["schemas"]["PreparationStepResponse"][];
        };
        /** @description The answer of a tool call */
        McpToolResult: {
            /** @description Text blocks of the result */
            content: string[];
            /**
             * @description Whether the tool reported a failure instead of a result
             * @example false
             */
            isError: boolean;
        };
        /** @description A tool offered by the MCP server */
        McpTool: {
            /**
             * @description Identifier of the tool
             * @example get_recipe
             */
            name: string;
            /**
             * @description Short human-readable title
             * @example Get a recipe
             */
            title?: string;
            /** @description What the tool does */
            description?: string;
            /** @description JSON Schema of the arguments the tool accepts */
            inputSchema: {
                [key: string]: unknown;
            };
        };
        /** @description Name, version and starting hint of the MCP server */
        McpServerInfo: {
            /**
             * @description Name the server reports
             * @example recipes
             */
            name: string;
            /**
             * @description Version the server reports
             * @example 0.0.1-SNAPSHOT
             */
            version: string;
            /** @description Where a caller should start, as sent to a protocol client */
            instructions: string;
        };
        /** @description A resource offered by the MCP server */
        McpResource: {
            /**
             * @description Address of the resource
             * @example recipes://docs/system
             */
            uri: string;
            /**
             * @description Identifier of the page
             * @example system
             */
            name: string;
            /** @description Title of the page */
            title?: string;
            /** @description One sentence about the page */
            description?: string;
            /**
             * @description Media type of the content
             * @example text/html
             */
            mimeType?: string;
        };
        /** @description The content of one resource */
        McpResourceContent: {
            /**
             * @description Address the content was read from
             * @example recipes://docs/system
             */
            uri: string;
            /**
             * @description Media type of the content
             * @example text/html
             */
            mimeType?: string;
            /** @description The content itself, absent if it is not text */
            text?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifier of the recipe
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested recipe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description No recipe exists for the given identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifier of the recipe
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeRequest"];
            };
        };
        responses: {
            /** @description The updated recipe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Request body invalid or malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description No recipe exists for the given identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifier of the recipe
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No recipe exists for the given identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All recipes, possibly an empty list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeRequest"];
            };
        };
        responses: {
            /** @description Recipe created; Location header points to it */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Request body invalid or malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetail"];
                };
            };
        };
    };
    callTool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Name of the tool, as returned by the tool list
                 * @example list_recipes
                 */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description The result of the tool, possibly marked as an error */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpToolResult"];
                };
            };
            /** @description No tool carries this name */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
    tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All tools, in the order a client should discover them */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpTool"][];
                };
            };
        };
    };
    server: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Name, version and instructions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpServerInfo"];
                };
            };
        };
    };
    resources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All resources, possibly an empty list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpResource"][];
                };
            };
        };
    };
    resourceContent: {
        parameters: {
            query: {
                /**
                 * @description URI of the resource, as returned by the resource list
                 * @example recipes://docs/system
                 */
                uri: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The content of the resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["McpResourceContent"][];
                };
            };
            /** @description No resource carries this URI */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                };
            };
        };
    };
}
