/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single recipe by its identifier */
        get: operations["getById"];
        /**
         * Replace an existing recipe
         * @description Replaces the recipe including its ingredients and preparation steps.
         */
        put: operations["update"];
        post?: never;
        /** Delete a recipe */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all recipes */
        get: operations["getAll"];
        put?: never;
        /**
         * Create a recipe
         * @description Creates a new recipe and returns it including the generated identifier.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A single ingredient of a recipe */
        Ingredient: {
            /**
             * @description Ingredient name
             * @example Spaghetti
             */
            name: string;
            /**
             * @description Amount of the ingredient
             * @example 500
             */
            quantity?: number;
            /**
             * @description Unit of the quantity
             * @example g
             */
            unit?: string;
        };
        /** @description A single preparation step; its order is the list position */
        PreparationStep: {
            /**
             * @description Textual instruction
             * @example Boil the pasta
             */
            instruction: string;
        };
        /** @description Recipe payload for create and update operations */
        RecipeRequest: {
            /**
             * @description Title of the recipe
             * @example Spaghetti Carbonara
             */
            title: string;
            /**
             * @description Free-text description
             * @example Classic Roman pasta
             */
            description?: string;
            /**
             * Format: int32
             * @description Number of servings
             * @example 4
             */
            servings?: number;
            /**
             * Format: int32
             * @description Preparation time in minutes
             * @example 25
             */
            prepTimeMinutes?: number;
            /**
             * @description Difficulty level
             * @example MEDIUM
             * @enum {string}
             */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /** @description Ingredients of the recipe */
            ingredients?: components["schemas"]["Ingredient"][];
            /** @description Preparation steps; their order in this list defines the position */
            steps?: components["schemas"]["PreparationStep"][];
        };
        /** @description Uniform error payload */
        ErrorResponse: {
            /**
             * Format: int32
             * @description HTTP status code
             * @example 404
             */
            status: number;
            /**
             * @description Short, machine-readable error label
             * @example NOT_FOUND
             */
            error: string;
            /**
             * @description Human-readable description
             * @example Recipe 42 not found
             */
            message: string;
            /** @description Per-field validation errors; empty unless a validation failed */
            fieldErrors: components["schemas"]["FieldError"][];
        };
        /** @description A single field-level validation error */
        FieldError: {
            /**
             * @description Name of the offending field
             * @example title
             */
            field: string;
            /**
             * @description Validation message
             * @example must not be blank
             */
            message: string;
        };
        /** @description A preparation step including its resolved order */
        PreparationStepResponse: {
            /**
             * Format: int32
             * @description 1-based order of the step
             * @example 1
             */
            position: number;
            /**
             * @description Textual instruction
             * @example Boil the pasta
             */
            instruction: string;
        };
        /** @description A persisted recipe */
        RecipeResponse: {
            /**
             * Format: int64
             * @description Database identifier
             * @example 1
             */
            id: number;
            /**
             * @description Title of the recipe
             * @example Spaghetti Carbonara
             */
            title: string;
            /**
             * @description Free-text description
             * @example Classic Roman pasta
             */
            description?: string;
            /**
             * Format: int32
             * @description Number of servings
             * @example 4
             */
            servings?: number;
            /**
             * Format: int32
             * @description Preparation time in minutes
             * @example 25
             */
            prepTimeMinutes?: number;
            /**
             * @description Difficulty level
             * @example MEDIUM
             * @enum {string}
             */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /** @description Ingredients of the recipe */
            ingredients: components["schemas"]["Ingredient"][];
            /** @description Preparation steps in ascending order */
            steps: components["schemas"]["PreparationStepResponse"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifier of the recipe
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested recipe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description No recipe exists for the given identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifier of the recipe
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeRequest"];
            };
        };
        responses: {
            /** @description The updated recipe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Request body invalid or malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No recipe exists for the given identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Identifier of the recipe
                 * @example 1
                 */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recipe deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No recipe exists for the given identifier */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All recipes, possibly an empty list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeRequest"];
            };
        };
        responses: {
            /** @description Recipe created; Location header points to it */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeResponse"];
                };
            };
            /** @description Request body invalid or malformed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
